---
- hosts: kube_control_plane
  become: yes
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: ingress-nginx
        api_version: v1
        kind: Namespace
        state: present
      vars:  
        ansible_python_interpreter: /usr/bin/python3
 
    - name: Tag prometheus monitoring
      shell: kubectl label node node2 monitoring=worker
      ignore_errors: yes

    - name: Clone a github repository
      git:
        repo: https://github.com/shevyf/prom_on_k8s_howto.git
        dest: ~/prometheus-k8s
        clone: yes     
      ignore_errors: yes

    - name: Apply the config-map manifest file for prometheus.
      community.kubernetes.k8s:
        state: present
        src: ~/prometheus-k8s/prometheus-config.yaml
      vars:
        ansible_python_interpreter: /usr/bin/python3

#    - name: install Pod network
#      become: yes
#      shell: kubectl create -f ~/prometheus-k8s/prometheus-roles.yml

    - name: Apply the clusterRole for Prometheus
      community.kubernetes.k8s:
        state: present
        src: ~/prometheus-k8s/prometheus-roles.yml
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Apply the deployment for Prometheus
      community.kubernetes.k8s:
        state: present
        src: ~/prometheus-k8s/prometheus-deployment.yaml
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Apply the service.yml for Prometheus
      community.kubernetes.k8s:
        state: present
        src: ~/prometheus-k8s/prometheus-nodeservice.yaml
      vars:
        ansible_python_interpreter: /usr/bin/python3
